# -*- coding: utf-8 -*-
"""Version_A_Group_Dynamic_ACO_FastOSM_SWEEP_2OPT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N9aSiVUwogCEvwxGO0z50Yk3x5pLOrIV

# Dynamic ACO - Group Project Conditions

Erwan AKKOCA

Jeremias KUHBERGER

Jiri LISKA

This notebook follows the following dynamic model :

- OpenStreetMap road graph through OSMnx.
- Driving network for `Centro, Madrid, Spain`.
- Nodes sampled directly from the road graph.
- Edge weights are `travel_time` in seconds.
- Every `N` iterations:
  - travel-time matrix is multiplied by random noise in `[0.9, 1.1]`;
  - a fraction of nodes becomes unavailable, e.g. `5%`.

This is the version to use when comparing ACO fairly with GA and PSO in the group.

## OSM setup

The notebook use a fast OSM strategy:

- Download/load the Madrid driving road graph with OSMnx.
- Keep the largest strongly connected component.
- Sample OSM road nodes directly from the graph.
- Build a shortest-path travel-time matrix using `travel_time`.
- Use the same ACO implementation style.

This avoids the slow POI-snapping loop over thousands of OSM places.

## 1. Install dependencies
"""

!pip -q install --upgrade osmnx
!pip -q install numpy pandas matplotlib

"""## 2. Imports and Google Drive cache"""

try:
    from google.colab import drive
    drive.mount('/content/drive')
    IN_COLAB = True
except Exception:
    IN_COLAB = False
    print("Drive not mounted. Running locally or without Drive.")

import os
import random
import time
from pathlib import Path
from dataclasses import dataclass
from typing import List, Tuple, Optional

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx
import osmnx as ox

if IN_COLAB:
    PROJECT_PATH = Path("/content/drive/MyDrive/project")
else:
    PROJECT_PATH = Path("./project")

PROJECT_PATH.mkdir(parents=True, exist_ok=True)
print("Cache/project path:", PROJECT_PATH)

"""## 3. OSM helper functions"""

def add_speeds_and_travel_times(G):
    try:
        G = ox.routing.add_edge_speeds(G)
        G = ox.routing.add_edge_travel_times(G)
    except AttributeError:
        G = ox.add_edge_speeds(G)
        G = ox.add_edge_travel_times(G)
    return G


def largest_strongly_connected_component(G):
    try:
        return ox.truncate.largest_component(G, strongly=True)
    except Exception:
        nodes = max(nx.strongly_connected_components(G), key=len)
        return G.subgraph(nodes).copy()


def to_digraph_min_travel_time(G):
    try:
        return ox.convert.to_digraph(G, weight="travel_time")
    except Exception:
        return G


def build_drive_graph(place, graph_path, network_type="drive", use_cache=True):
    ox.settings.use_cache = True
    ox.settings.log_console = False

    if graph_path.exists() and use_cache:
        print("Loading cached graph:", graph_path)
        G = ox.load_graphml(graph_path)
        edge_data = next(iter(G.edges(data=True)), None)
        if edge_data is not None and "travel_time" not in edge_data[2]:
            G = add_speeds_and_travel_times(G)
    else:
        print("Downloading OSM drive graph for:", place)
        G = ox.graph_from_place(place, network_type=network_type, simplify=True)
        G = add_speeds_and_travel_times(G)
        ox.save_graphml(G, graph_path)
        print("Saved graph:", graph_path)

    G = largest_strongly_connected_component(G)
    G = to_digraph_min_travel_time(G)
    return G


def sample_road_nodes(G, node_count, seed):
    nodes = list(G.nodes)
    if node_count < 0 or node_count >= len(nodes):
        return nodes
    rng = random.Random(seed)
    return rng.sample(nodes, node_count)


def build_time_matrix(G, nodes, inf_cost):
    n = len(nodes)
    matrix = np.full((n, n), inf_cost, dtype=float)

    for i, source in enumerate(nodes):
        if i % 10 == 0:
            print(f"Computing Dijkstra {i + 1}/{n}")

        lengths = nx.single_source_dijkstra_path_length(
            G,
            source,
            weight="travel_time",
        )

        for j, target in enumerate(nodes):
            if i == j:
                matrix[i, j] = 0.0
            else:
                matrix[i, j] = float(lengths.get(target, inf_cost))

    unreachable = int(np.sum(matrix >= inf_cost / 2))
    if unreachable > 0:
        print("WARNING: unreachable entries:", unreachable)
    else:
        print("All sampled nodes are mutually reachable.")

    return matrix


def tour_to_route_nodes(G, node_ids, start_index, tour):
    """
    Expand the abstract TSP tour into real OSM road nodes.

    The algorithm returns a tour as indices of sampled nodes. Consecutive sampled
    nodes are not necessarily adjacent in the street graph, so each hop is expanded
    using the OSM shortest path.
    """
    if tour is None or len(tour) == 0:
        raise ValueError("Tour is empty. Run ACO before plotting.")

    ordered_indices = [start_index] + [i for i in tour if i != start_index] + [start_index]
    osm_nodes = [node_ids[i] for i in ordered_indices]

    route_nodes = []
    skipped_segments = 0

    for u, v in zip(osm_nodes, osm_nodes[1:]):
        segment = ox.shortest_path(G, u, v, weight="travel_time")

        if segment is None or len(segment) == 0:
            skipped_segments += 1
            continue

        route_nodes.extend(segment[1:] if route_nodes else segment)

    if skipped_segments > 0:
        print(f"Warning: skipped {skipped_segments} unreachable route segments.")

    if len(route_nodes) < 2:
        raise ValueError("Could not build a drawable route from the tour.")

    return route_nodes


def plot_tour_on_graph(G, node_ids, start_index, tour, route_color="red", title=None):
    """
    Robust final route plot.

    Why not use ox.plot_graph_route?
    The notebook converts the OSM graph to a DiGraph for computation. Some OSMnx
    plotting functions expect a MultiDiGraph with edge keys, which can produce:
        OutEdgeView.__call__() got an unexpected keyword argument 'keys'

    This function plots the route directly with Matplotlib from OSM node coordinates,
    so it works with the DiGraph used in the notebook.
    """
    route_nodes = tour_to_route_nodes(G, node_ids, start_index, tour)

    route_x = [G.nodes[n]["x"] for n in route_nodes]
    route_y = [G.nodes[n]["y"] for n in route_nodes]

    # Delivery/sample node coordinates for context.
    ordered_indices = [start_index] + [i for i in tour if i != start_index]
    sample_osm_nodes = [node_ids[i] for i in ordered_indices if node_ids[i] in G.nodes]
    sample_x = [G.nodes[n]["x"] for n in sample_osm_nodes]
    sample_y = [G.nodes[n]["y"] for n in sample_osm_nodes]

    plt.figure(figsize=(9, 9))

    # Light background road graph. Limited linewidth keeps it readable.
    for u, v in G.edges():
        try:
            x1, y1 = G.nodes[u]["x"], G.nodes[u]["y"]
            x2, y2 = G.nodes[v]["x"], G.nodes[v]["y"]
            plt.plot([x1, x2], [y1, y2], color="lightgray", linewidth=0.25, alpha=0.25, zorder=1)
        except Exception:
            continue

    # ACO route.
    plt.plot(route_x, route_y, color=route_color, linewidth=2.5, alpha=0.95, zorder=3, label="ACO route")

    # Sampled delivery nodes and depot.
    plt.scatter(sample_x, sample_y, s=18, alpha=0.55, zorder=4, label="Sampled nodes")

    start_osm = node_ids[start_index]
    plt.scatter(
        [G.nodes[start_osm]["x"]],
        [G.nodes[start_osm]["y"]],
        s=120,
        marker="s",
        zorder=5,
        label="Depot / start",
    )

    plt.xlabel("Longitude")
    plt.ylabel("Latitude")
    if title:
        plt.title(title)
    else:
        plt.title("ACO route on Madrid OSM road graph")
    plt.grid(True, alpha=0.2)
    plt.legend()
    plt.tight_layout()
    plt.show()

    return route_nodes

"""## 4. Configuration — group version"""

SAMPLE_SEED = 42
DYNAMICS_SEED = 123
ACO_SEED = 42

PLACE = "Centro, Madrid, Spain"
NETWORK_TYPE = "drive"
GRAPH_PATH = PROJECT_PATH / "centro_madrid_drive.graphml"

NODE_COUNT = 80
START_INDEX = 0

UPDATE_INTERVAL = 10
NOISE_RANGE = (0.9, 1.1)
DROP_FRACTION = 0.05

N_ITERATIONS = 200
N_ANTS = None

ALPHA = 1.0
BETA = 4.0
RHO = 0.30
EVENT_RHO = 0.60
EVENT_WINDOW = 3
TOP_K = 5
Q = 100.0
ELITE_WEIGHT = 2.0

INF_COST = 1e12

random.seed(SAMPLE_SEED)
np.random.seed(SAMPLE_SEED)

"""## 5. Build graph, sample nodes, and compute travel-time matrix"""

G = build_drive_graph(PLACE, GRAPH_PATH, network_type=NETWORK_TYPE, use_cache=True)
print("Graph nodes:", len(G.nodes))
print("Graph edges:", len(G.edges))

node_ids = sample_road_nodes(G, NODE_COUNT, SAMPLE_SEED)
print("Sampled nodes:", len(node_ids))

base_matrix = build_time_matrix(G, node_ids, INF_COST)
finite = base_matrix[(base_matrix > 0) & (base_matrix < INF_COST / 2)]
print("Travel-time range:", round(finite.min(), 2), "to", round(finite.max(), 2), "seconds")

"""## 6. Dynamic environment — group version"""

class GroupDynamicRoadTSP:
    def __init__(
        self,
        base_matrix,
        start_index=0,
        update_interval=10,
        noise_range=(0.9, 1.1),
        drop_fraction=0.05,
        dynamics_seed=123,
        inf_cost=1e12,
    ):
        self.base_matrix = base_matrix.copy()
        self.current_matrix = base_matrix.copy()
        self.start_index = start_index
        self.update_interval = update_interval
        self.noise_range = noise_range
        self.drop_fraction = drop_fraction
        self.inf_cost = inf_cost
        self.rng = np.random.default_rng(dynamics_seed)
        self.available_mask = np.ones(base_matrix.shape[0], dtype=bool)
        self.available_mask[start_index] = True

    @property
    def n(self):
        return self.base_matrix.shape[0]

    def update(self, iteration):
        if iteration == 0 or iteration % self.update_interval != 0:
            return False

        low, high = self.noise_range
        noise = self.rng.uniform(low, high, size=self.base_matrix.shape)
        self.current_matrix = self.base_matrix * noise
        np.fill_diagonal(self.current_matrix, 0.0)

        self.available_mask = np.ones(self.n, dtype=bool)
        self.available_mask[self.start_index] = True

        candidates = np.array([i for i in range(self.n) if i != self.start_index], dtype=int)
        drop_count = int(candidates.size * self.drop_fraction)

        if drop_count > 0:
            drop_indices = self.rng.choice(candidates, size=drop_count, replace=False)
            self.available_mask[drop_indices] = False

        return True

    def filter_tour(self, tour):
        return [
            i for i in tour
            if i != self.start_index and self.available_mask[i]
        ]

    def route_cost(self, tour):
        filtered = self.filter_tour(tour)
        if not filtered:
            return 0.0

        ordered = [self.start_index] + filtered + [self.start_index]
        total = 0.0

        for a, b in zip(ordered[:-1], ordered[1:]):
            cost = self.current_matrix[a, b]
            if cost >= self.inf_cost / 2:
                return self.inf_cost
            total += cost

        return float(total)


def nearest_neighbor_tour(matrix, start_index, available_mask, inf_cost):
    unvisited = np.flatnonzero(available_mask).tolist()
    if start_index in unvisited:
        unvisited.remove(start_index)

    tour = []
    current = start_index

    while unvisited:
        feasible = [i for i in unvisited if matrix[current, i] < inf_cost / 2]
        if feasible:
            nxt = min(feasible, key=lambda i: matrix[current, i])
        else:
            nxt = min(unvisited, key=lambda i: matrix[current, i])

        tour.append(nxt)
        unvisited.remove(nxt)
        current = nxt

    return tour


def run_nearest_neighbor_baseline(env, iterations, recompute_on_update=True):
    current_tour = nearest_neighbor_tour(env.current_matrix, env.start_index, env.available_mask, env.inf_cost)
    best_tour = current_tour[:]
    best_cost = env.route_cost(current_tour)

    history = [best_cost]
    updates = []

    for iteration in range(1, iterations + 1):
        updated = env.update(iteration)

        if updated:
            updates.append(iteration)
            if recompute_on_update:
                current_tour = nearest_neighbor_tour(
                    env.current_matrix,
                    env.start_index,
                    env.available_mask,
                    env.inf_cost,
                )

        cost = env.route_cost(current_tour)

        if cost < best_cost:
            best_cost = cost
            best_tour = current_tour[:]

        history.append(cost)

    return {
        "best_tour": best_tour,
        "best_cost": best_cost,
        "history": history,
        "updates": updates,
    }

"""## 7. Dynamic ACO"""

class DynamicACO:
    def __init__(
        self,
        n_nodes,
        start_index,
        alpha=1.0,
        beta=4.0,
        rho=0.30,
        event_rho=0.60,
        event_window=3,
        q=100.0,
        elite_weight=2.0,
        top_k=5,
        n_ants=None,
        seed=42,
    ):
        self.n_nodes = n_nodes
        self.start_index = start_index
        self.alpha = alpha
        self.beta = beta
        self.rho = rho
        self.event_rho = event_rho
        self.event_window = event_window
        self.q = q
        self.elite_weight = elite_weight
        self.top_k = top_k
        self.n_ants = n_ants
        self.rng = random.Random(seed)

        self.pheromone = np.ones((n_nodes, n_nodes), dtype=float)
        np.fill_diagonal(self.pheromone, 0.0)

    def choose_next_node(self, current, unvisited, matrix, inf_cost):
        weights = []

        for node in unvisited:
            distance = matrix[current, node]
            if distance >= inf_cost / 2:
                weight = 0.0
            else:
                tau = self.pheromone[current, node] ** self.alpha
                eta = (1.0 / (distance + 1e-9)) ** self.beta
                weight = tau * eta
            weights.append(weight)

        total = sum(weights)

        if total <= 0:
            feasible = [node for node in unvisited if matrix[current, node] < inf_cost / 2]
            if feasible:
                return min(feasible, key=lambda node: matrix[current, node])
            return self.rng.choice(unvisited)

        threshold = self.rng.random() * total
        cumulative = 0.0

        for node, weight in zip(unvisited, weights):
            cumulative += weight
            if cumulative >= threshold:
                return node

        return unvisited[-1]

    def construct_tour(self, matrix, available_mask, inf_cost):
        unvisited = np.flatnonzero(available_mask).tolist()
        if self.start_index in unvisited:
            unvisited.remove(self.start_index)

        tour = []
        current = self.start_index

        while unvisited:
            next_node = self.choose_next_node(current, unvisited, matrix, inf_cost)
            tour.append(next_node)
            unvisited.remove(next_node)
            current = next_node

        return tour

    def evaporate(self, rho):
        self.pheromone *= (1.0 - rho)
        np.fill_diagonal(self.pheromone, 0.0)
        self.pheromone = np.maximum(self.pheromone, 1e-12)

    def deposit(self, tour, cost, multiplier=1.0):
        if tour is None or cost <= 0:
            return
        ordered = [self.start_index] + [i for i in tour if i != self.start_index] + [self.start_index]
        delta = multiplier * self.q / cost

        for a, b in zip(ordered[:-1], ordered[1:]):
            self.pheromone[a, b] += delta
            self.pheromone[b, a] += delta

    def update_pheromone(self, tours_and_costs, best_tour, best_cost, rho, inf_cost):
        self.evaporate(rho)

        feasible = [(t, c) for t, c in tours_and_costs if c < inf_cost / 2]

        for tour, cost in sorted(feasible, key=lambda x: x[1])[: self.top_k]:
            self.deposit(tour, cost, multiplier=1.0)

        if best_tour is not None and best_cost < inf_cost / 2:
            self.deposit(best_tour, best_cost, multiplier=self.elite_weight)

class GroupDynamicACO(DynamicACO):
    def run(self, env, iterations):
        best_tour = None
        best_cost = float("inf")
        history = []
        updates = []
        event_timer = 0
        infeasible_rejected = 0

        for iteration in range(iterations + 1):
            updated = env.update(iteration)

            if updated:
                updates.append(iteration)
                event_timer = self.event_window

                if best_tour is not None:
                    best_cost = env.route_cost(best_tour)
                    if best_cost >= env.inf_cost / 2:
                        best_tour = None
                        best_cost = float("inf")

            ants = self.n_ants if self.n_ants is not None else int(env.available_mask.sum())
            tours_and_costs = []

            for _ in range(ants):
                tour = self.construct_tour(env.current_matrix, env.available_mask, env.inf_cost)
                cost = env.route_cost(tour)

                if cost >= env.inf_cost / 2:
                    infeasible_rejected += 1
                    continue

                tours_and_costs.append((tour, cost))

                if cost < best_cost:
                    best_tour = tour[:]
                    best_cost = cost

            rho_used = self.event_rho if event_timer > 0 else self.rho
            self.update_pheromone(tours_and_costs, best_tour, best_cost, rho_used, env.inf_cost)

            history.append(best_cost)

            if event_timer > 0:
                event_timer -= 1

        return {
            "best_tour": best_tour,
            "best_cost": best_cost,
            "history": history,
            "updates": updates,
            "infeasible_rejected": infeasible_rejected,
        }

"""## 8. Run baseline and ACO"""

baseline_env = GroupDynamicRoadTSP(
    base_matrix=base_matrix,
    start_index=START_INDEX,
    update_interval=UPDATE_INTERVAL,
    noise_range=NOISE_RANGE,
    drop_fraction=DROP_FRACTION,
    dynamics_seed=DYNAMICS_SEED,
    inf_cost=INF_COST,
)

baseline_result = run_nearest_neighbor_baseline(baseline_env, N_ITERATIONS)
print("Baseline best cost:", round(baseline_result["best_cost"], 2), "seconds")

aco_env = GroupDynamicRoadTSP(
    base_matrix=base_matrix,
    start_index=START_INDEX,
    update_interval=UPDATE_INTERVAL,
    noise_range=NOISE_RANGE,
    drop_fraction=DROP_FRACTION,
    dynamics_seed=DYNAMICS_SEED,
    inf_cost=INF_COST,
)

aco = GroupDynamicACO(
    n_nodes=base_matrix.shape[0],
    start_index=START_INDEX,
    alpha=ALPHA,
    beta=BETA,
    rho=RHO,
    event_rho=EVENT_RHO,
    event_window=EVENT_WINDOW,
    q=Q,
    elite_weight=ELITE_WEIGHT,
    top_k=TOP_K,
    n_ants=N_ANTS,
    seed=ACO_SEED,
)

t0 = time.time()
aco_result = aco.run(aco_env, N_ITERATIONS)
runtime = time.time() - t0

print("ACO best cost:", round(aco_result["best_cost"], 2), "seconds")
print("ACO runtime:", round(runtime, 2), "seconds")
print("Dynamic updates:", aco_result["updates"][:10], "...")
print("Infeasible ant tours rejected:", aco_result["infeasible_rejected"])

"""## 9. Compare and plot"""

improvement = 100 * (baseline_result["best_cost"] - aco_result["best_cost"]) / baseline_result["best_cost"]

summary = pd.DataFrame([
    {
        "method": "Nearest neighbor",
        "best_cost_seconds": baseline_result["best_cost"],
        "best_cost_minutes": baseline_result["best_cost"] / 60,
    },
    {
        "method": "Dynamic ACO",
        "best_cost_seconds": aco_result["best_cost"],
        "best_cost_minutes": aco_result["best_cost"] / 60,
    },
])

print("ACO improvement over baseline:", round(improvement, 2), "%")
summary

plt.figure(figsize=(10, 4))
plt.plot(baseline_result["history"], label="Nearest neighbor")
plt.plot(aco_result["history"], label="Dynamic ACO")

for it in aco_result["updates"]:
    plt.axvline(it, color="gray", alpha=0.12)

plt.xlabel("Iteration")
plt.ylabel("Cost (seconds)")
plt.title("Group-version dynamic model: noise + node unavailability")
plt.grid(True, alpha=0.3)
plt.legend()
plt.show()

# Final route plot
# This cell uses the robust Matplotlib plot_tour_on_graph defined above.
# It does not call ox.plot_graph_route, so it works with the DiGraph used for computation.

if aco_result.get("best_tour") is None or len(aco_result["best_tour"]) == 0:
    raise ValueError("No ACO tour found. Run the ACO cells before this plot.")

route_nodes = plot_tour_on_graph(
    G,
    node_ids,
    START_INDEX,
    aco_result["best_tour"],
    route_color="red",
    title="Best ACO route — group dynamic model",
)

print("Final route plotted successfully.")
print("Number of OSM road nodes in plotted route:", len(route_nodes))

"""## 10. Parameter variation study

This section tests whether some ACO parameter settings perform better under the **same group dynamic environment**.

We keep the environment fixed:

```text
update_interval = 10
noise_range = (0.9, 1.1)
drop_fraction = 0.05
```

Only ACO parameters are varied:

- `alpha`: pheromone influence
- `beta`: distance/visibility influence
- `rho`: normal evaporation rate
- `event_rho`: stronger evaporation after a dynamic update

This is useful for showing that ACO is not a single fixed method; its behavior depends on the exploration/exploitation balance.
"""

def run_aco_parameter_case(params, seed=0, iterations=N_ITERATIONS):
    """Run one ACO parameter setting on the same group dynamic model."""
    env = GroupDynamicRoadTSP(
        base_matrix=base_matrix,
        start_index=START_INDEX,
        update_interval=UPDATE_INTERVAL,
        noise_range=NOISE_RANGE,
        drop_fraction=DROP_FRACTION,
        dynamics_seed=DYNAMICS_SEED,
        inf_cost=INF_COST,
    )

    model = GroupDynamicACO(
        n_nodes=base_matrix.shape[0],
        start_index=START_INDEX,
        alpha=params["alpha"],
        beta=params["beta"],
        rho=params["rho"],
        event_rho=params["event_rho"],
        event_window=params.get("event_window", EVENT_WINDOW),
        q=Q,
        elite_weight=ELITE_WEIGHT,
        top_k=TOP_K,
        n_ants=params.get("n_ants", N_ANTS),
        seed=seed,
    )

    t0 = time.time()
    result = model.run(env, iterations)
    runtime = time.time() - t0

    return {
        "seed": seed,
        "alpha": params["alpha"],
        "beta": params["beta"],
        "rho": params["rho"],
        "event_rho": params["event_rho"],
        "event_window": params.get("event_window", EVENT_WINDOW),
        "n_ants": params.get("n_ants", N_ANTS),
        "best_cost_seconds": result["best_cost"],
        "best_cost_minutes": result["best_cost"] / 60,
        "runtime_seconds": runtime,
        "infeasible_rejected": result["infeasible_rejected"],
    }

# Small sweep designed to stay reasonable in Colab.
# Increase the seeds/configurations if you have more time.

param_grid = [
    {"alpha": 1.0, "beta": 2.0, "rho": 0.30, "event_rho": 0.60},
    {"alpha": 1.0, "beta": 4.0, "rho": 0.30, "event_rho": 0.60},  # original setting
    {"alpha": 1.0, "beta": 6.0, "rho": 0.30, "event_rho": 0.60},
    {"alpha": 1.5, "beta": 4.0, "rho": 0.20, "event_rho": 0.70},
    {"alpha": 0.8, "beta": 5.0, "rho": 0.50, "event_rho": 0.70},
]

sweep_seeds = [0, 1, 2]

rows = []
for params in param_grid:
    for seed in sweep_seeds:
        print("Running:", params, "seed:", seed)
        rows.append(run_aco_parameter_case(params, seed=seed))

sweep_df = pd.DataFrame(rows)
sweep_df

sweep_summary = (
    sweep_df
    .groupby(["alpha", "beta", "rho", "event_rho", "event_window", "n_ants"], dropna=False)
    .agg(
        mean_cost_minutes=("best_cost_minutes", "mean"),
        std_cost_minutes=("best_cost_minutes", "std"),
        best_cost_minutes=("best_cost_minutes", "min"),
        mean_runtime_seconds=("runtime_seconds", "mean"),
        mean_infeasible_rejected=("infeasible_rejected", "mean"),
    )
    .reset_index()
    .sort_values("mean_cost_minutes")
)

sweep_summary

plt.figure(figsize=(10, 4))

labels = [
    f"a={r.alpha}, b={r.beta}, rho={r.rho}, erho={r.event_rho}"
    for _, r in sweep_summary.iterrows()
]

plt.bar(range(len(sweep_summary)), sweep_summary["mean_cost_minutes"])
plt.xticks(range(len(sweep_summary)), labels, rotation=35, ha="right")
plt.ylabel("Mean best cost (minutes)")
plt.title("ACO parameter variation study")
plt.grid(axis="y", alpha=0.3)
plt.tight_layout()
plt.show()

best_params_row = sweep_summary.iloc[0]
print("Best average parameter setting:")
display(best_params_row.to_frame().T)

"""## 11. Concatenated method: Dynamic ACO + 2-opt

This is a small hybrid/concatenated method:

```text
Dynamic ACO = global search
2-opt = local route refinement
```

ACO finds a good route under dynamic conditions. Then 2-opt tries to improve the final order by reversing route segments. If a reversal reduces the route cost in the final dynamic state, it is kept.
"""

def build_final_environment():
    """Recreate the same final dynamic environment used at N_ITERATIONS."""
    final_env = GroupDynamicRoadTSP(
        base_matrix=base_matrix,
        start_index=START_INDEX,
        update_interval=UPDATE_INTERVAL,
        noise_range=NOISE_RANGE,
        drop_fraction=DROP_FRACTION,
        dynamics_seed=DYNAMICS_SEED,
        inf_cost=INF_COST,
    )

    for iteration in range(1, N_ITERATIONS + 1):
        final_env.update(iteration)

    return final_env


def two_opt_improve(tour, env, max_passes=5):
    """
    Simple 2-opt improvement on the final active route.

    The tour does not include the depot. Unavailable nodes are filtered by env.
    """
    best = env.filter_tour(tour)
    best_cost = env.route_cost(best)

    if not best or best_cost >= env.inf_cost / 2:
        return best, best_cost, 0

    improvements = 0

    for _ in range(max_passes):
        improved_this_pass = False

        for i in range(len(best) - 2):
            for j in range(i + 2, len(best) + 1):
                candidate = best[:]
                candidate[i:j] = reversed(candidate[i:j])

                cost = env.route_cost(candidate)

                if cost < best_cost:
                    best = candidate
                    best_cost = cost
                    improvements += 1
                    improved_this_pass = True

        if not improved_this_pass:
            break

    return best, best_cost, improvements


final_env = build_final_environment()

improved_tour, improved_cost, n_improvements = two_opt_improve(
    aco_result["best_tour"],
    final_env,
    max_passes=5,
)

aco_final_cost = final_env.route_cost(aco_result["best_tour"])

print("ACO final-state cost:", round(aco_final_cost, 2), "seconds", "|", round(aco_final_cost / 60, 2), "minutes")
print("ACO + 2-opt cost:", round(improved_cost, 2), "seconds", "|", round(improved_cost / 60, 2), "minutes")
print("2-opt accepted improvements:", n_improvements)

if aco_final_cost < INF_COST / 2:
    two_opt_gain = 100 * (aco_final_cost - improved_cost) / aco_final_cost
    print("2-opt improvement over ACO:", round(two_opt_gain, 2), "%")
else:
    print("ACO final route was infeasible in final state.")

hybrid_summary = pd.DataFrame([
    {
        "method": "Dynamic ACO",
        "cost_seconds": aco_final_cost,
        "cost_minutes": aco_final_cost / 60,
    },
    {
        "method": "Dynamic ACO + 2-opt",
        "cost_seconds": improved_cost,
        "cost_minutes": improved_cost / 60,
    },
])

hybrid_summary

plt.figure(figsize=(6, 4))
plt.bar(hybrid_summary["method"], hybrid_summary["cost_minutes"])
plt.ylabel("Cost in final dynamic state (minutes)")
plt.title("Concatenated method: ACO vs ACO + 2-opt")
plt.grid(axis="y", alpha=0.3)
plt.tight_layout()
plt.show()

# Optional: plot the improved ACO + 2-opt route.
plot_tour_on_graph(
    G,
    node_ids,
    START_INDEX,
    improved_tour,
    route_color="blue",
    title="Best route after ACO + 2-opt refinement",
)

"""## 12. interpretation

- The parameter sweep tests whether better ACO behavior can be obtained by changing pheromone importance, distance importance, and evaporation.
- The ACO + 2-opt method is a concatenated hybrid method: ACO explores globally, then 2-opt refines locally.
- If ACO + 2-opt improves the cost, it means ACO found a good region but local route refinement still helped.
- If 2-opt does not improve much, it means ACO already found a locally strong route.
"""